/**
 * Party 1 - Secure Share Storage Module
 * 
 * Stores Party 1's pre-computed shares and partial keys received from the main website.
 * This module acts as secure storage for shares that are generated by the main website using SSS.
 * 
 * Responsibilities:
 * - Store pre-computed Party 1's share (received from main website)
 * - Retrieve stored shares when needed
 * - Store and retrieve partial keys from main website
 * 
 * Security considerations:
 * - Shares are stored in volatile memory (consider persistent storage in production)
 * - Each share alone is computationally infeasible to crack
 */

/**
 * Secure value interface representing MPC-shared data
 * Contains shares for Party 1 and Party 2 (both needed to reconstruct)
 * Note: Generated by main website using Shamir's Secret Sharing
 */
export interface SecureValue {
  id: string;
  type: 'MPC_SHARE';
  shares: {
    party1: string; // Party 1's share (hex-encoded)
    party2: string; // Party 2's share (hex-encoded)
  };
  metadata: {
    fieldName: string;
    timestamp: number;
    partyCount: number;
    threshold: number; // Both shares needed (2-of-2)
  };
}

/**
 * Party 1 Store - manages storage for this party
 * 
 * Responsibilities:
 * - Store pre-computed Party 1's share (received from main website)
 * - Store partial keys received from main website
 * - Retrieve stored shares when requested by other websites
 */
export class Party1Store {
  // In production, use persistent storage (Redis, database, etc.)
  private readonly party1Shares: Map<string, string> = new Map();
  // Store partial keys received from main website
  private readonly partialKeys: Map<string, string> = new Map();


  /**
   * Store a pre-computed party1 share (hex-encoded)
   * Used when receiving already-split shares from main website
   * 
   * @param shareId Unique identifier
   * @param shareHex Hex-encoded share (with or without 0x prefix)
   * @throws Error if share is invalid
   */
  storeShareHex(shareId: string, shareHex: string): void {
    if (!shareId || !shareHex) {
      throw new Error('shareId and shareHex cannot be empty');
    }

    try {
      const normalized = shareHex.startsWith('0x') ? shareHex.slice(2) : shareHex;
      // Validate hex format
      if (!/^[0-9a-fA-F]+$/.test(normalized)) {
        throw new Error('Invalid hex format');
      }
      // Store as hex string directly
      this.party1Shares.set(shareId, normalized);
    } catch (err) {
      throw new Error(`Failed to store share: ${err instanceof Error ? err.message : String(err)}`);
    }
  }

  /**
   * Retrieve this party's share for a given ID
   * 
   * @param shareId Share identifier
   * @returns Hex-encoded share or undefined if not found
   */
  getShareHex(shareId: string): string | undefined {
    return this.party1Shares.get(shareId);
  }

  /**
   * Store partial key received from main website
   * Used to reconstruct full encryption key incrementally
   * 
   * @param keyId Unique key identifier
   * @param partialKey Partial key (portion from main website)
   * @throws Error if parameters are empty or invalid
   */
  storePartialKey(keyId: string, partialKey: string): void {
    if (!keyId || !partialKey) {
      throw new Error('keyId and partialKey cannot be empty');
    }
    // Validate partialKey format (should be hex or base64)
    if (!/^[0-9a-fA-F]+$/.test(partialKey) && !/^[A-Za-z0-9+/=]+$/.test(partialKey)) {
      throw new Error('partialKey must be hex or base64 encoded');
    }
    this.partialKeys.set(keyId, partialKey);
  }

  /**
   * Retrieve partial key stored from main website
   * 
   * @param keyId Key identifier
   * @returns Partial key or undefined if not found
   */
  getPartialKey(keyId: string): string | undefined {
    return this.partialKeys.get(keyId);
  }
}

// Singleton instance
export const party1 = new Party1Store();
